### ISSUE TITLE
Flow Diagram step0

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#27]
**Is your feature request related to a problem? Please describe.**
According to meeting 15.12.2023

add a flow diagramm of step0 process 

**Describe the solution you'd like**
add a screenshot of your flow, so I can adapt https://github.com/swisstopo/topo-satromo/blob/main/satromo_processor.drawio

**Comment by gilliM** [comment]
[flow_step0.pdf](https://github.com/swisstopo/topo-satromo/files/13713074/flow_step0.pdf)

**Comment by gilliM** [comment]
Let me know if you want to PPTX version, or any other change

**Comment by davidoesch** [comment]
@gilliM 

I updated the data flow in [satromo_processor.drawio](https://github.com/swisstopo/topo-satromo/blob/step0/satromo_processor.drawio)  as I understand it.  it is work in progress regarding the layout.
I
Regarding clouds and shadow I have questions
: "clouds" are treated in  def maskCloudsAndShadow
https://github.com/swisstopo/topo-satromo/blob/33711a8269dd15a28174594c6a1a2fda2437d336/step0_processors/step0_processor_s2_sr.py#L170

Questions
- [ ] : cloud threshold: we ommit all sceenes which have more than 50% of cloud coverage: https://github.com/swisstopo/topo-satromo/blob/33711a8269dd15a28174594c6a1a2fda2437d336/step0_processors/step0_processor_s2_sr.py#L177, is this correct? 50% seems quite low to me, @HendrikWulf @gilliM : what would make  sense from your perspective? 90% ?




- [ ] IF condition: if the image is cloudy : I  do not understand the code: where  in def maskCloudsAndShadows  
![image](https://github.com/swisstopo/topo-satromo/assets/4577727/fd6e71c4-da7f-4154-a891-b92b351cbaa6) do you exit  the  processor def generate_<sensor>_<prod>_mosaic_for_single_date if there is too much cloud&shadow above the threshold? or ist it done in https://github.com/swisstopo/topo-satromo/blob/1bda99f45d7d5e01823e25d3d4169cef5387c7c7/step0_processors/step0_processor_s2_sr.py#L366 ? where does the threshold kick in?


- [ ] EXPORT cloudy:  Does it make sense to export an asset if it is "cloudy" as ashown in your docu? the image is then not used or do I understand the code wrong? As I understand the code  is not exporting cloudy assets. which makes sense

![image](https://github.com/swisstopo/topo-satromo/assets/4577727/c6f74d31-d05f-4d9e-bffa-1ef93370e80f)

**Comment by gilliM** [comment]
1) from the code: https://github.com/swisstopo/topo-satromo/blob/cc77fe58e28fdadf2c47101f65a3368d7f9f0a47/step0_processors/step0_processor_s2_sr.py#L367 we ignore images with > 98% clouds. I would go lower to at max 80% personally·

2) it's here: https://github.com/swisstopo/topo-satromo/blob/cc77fe58e28fdadf2c47101f65a3368d7f9f0a47/step0_processors/step0_processor_s2_sr.py#L370 + the return just the line after the end the step0 script. It's after the mosaic because the threshold (98% here) is applied on the whole mosaic and not per scene: we decide together for the whole swath if we want to process it or not.

3) the code does not export cloudy asset. The idea behind is to save some money by not processing and storing useless cloud pixels.

**Comment by davidoesch** [comment]
1) thanks, did not understand  ",2"  now i do fixed with 8a5e0c82a190915868e502030f872f5ee3d911a7

**Comment by davidoesch** [comment]
2. thanks clear now for me
3. celar to me, the image was irritating me
