### ISSUE TITLE
Filenaming convention: rename  exported files

### ISSUE THREAD

**Issue by davidoesch** [swisstopo/topo-satromo#29]
**Describe the solution you'd like**
Rename the exports to 

- [x] - 2023-10-16T103021\S2_mosaic_2023-10-16T103021_cloudprobability-10m.tif
- [x] -2023-10-16T103021\ S2-L2A_mosaic_2023-10-16T103021_bands-10m.tif
- [ ] -2023-10-16T103021\S2-L2A_mosaic_2023-10-16T103021_bands-20m.tif
- [x] -2023-10-16T103021\S2-L2A_mosaic_2023-10-16T103021_masks-10m.tif
- [x] -2023-10-16T103021\S2-L2A_mosaic_2023-10-16T103021_metadata.csv
- [x] -2023-10-16T103021\S2-L2A_mosaic_2023-10-16T103021_registration-10m.tif
- [x] -2023-10-16T103021\S2-L2A_mosaic_2023-10-16T103021_thumbnail.jpg

similar: to NDVI

**Comment by gilliM** [comment]
I'm changed the asset names according to the above convention.
Should I also adapt the <asset to TIFF> exports ?

**Comment by davidoesch** [comment]
Since you are at it: Change as well the exports, will assign the ticket to you

**Comment by gilliM** [comment]
It's actually a bit more complex for me than what i thought, because i'm not sure of what you want exactly in the process (should the base name come from the custom asset collection or from the configuration directly for example, does it even matter...)
Also I'm not sure about the link with the publisher.

I've now the following for images in the personal collection:
          projects/satromo-exolabs/assets/col_s2_sr/S2-L2A_mosaic_2023-10-03TT101841_bands-10m
    and this for the exported TIFFs:
          S2-L2A_mosaic_2023-10-03TT101841_bands-10mquadrant1.tif
          ...
          S2-L2A_mosaic_2023-10-03TT101841_bands-10mquadrant4.tif
    I've renamed the mask60 export that I had to the _masks-10m.tif as proposed in the list above.

I saw that up to now, there were 2 dates in the file name. There were both linked to the processing date, but maybe you wanted a 'processed date' in the file or in the product ? for example if you launch now a product for 2022, you would like <product>_2022-mm-ddTHHMMSS_produced_on_20231922T120243.tif

For NDVI, i'm not sure what you want:
- do you want to indicate first and last image in the file name, or maybe the last date + the temporal coverage interval ? or maybe nothing ?

**Comment by davidoesch** [comment]
thanks for reaching out

- [ ]  base name come from the config file and are then used in asset export and file export
- [ ] "2023-10-03TT101841" should be "2023-10-03**T**101841" only on "T"
- [X] "renamed the mask60 export that I had to the _masks-10m.tif" - perfect
- [ ] `"I saw that up to now, there were 2 dates in the file name. There were both linked to the processing date, but maybe you wanted a 'processed date' in the file or in the product ? for example if you launch now a product for 2022, you would like _2022-mm-ddTHHMMSS_produced_on_20231922T120243.tif"`
--> we remove the "runYYYYMMDD" part. Not needed. the necesssary metadata is in the _metadata.csv so filename as sted in the initial description above  the goal for L1C and L2A

- [ ] for NDVI  : use `prefix`_mosaic_YYYY-MM-DDT235959_`spatial_scale_export`m e.g. Sentinel_NDVI-MAX_SR_CloudFree_crop_mosaic_2023-10-16T235959_10m.tif  Tmperoal coverage I'll add later in an _metadata.csv

question:
did you add alread the band -20m as well in export and asset?

When you done let me know, ship it

**Comment by gilliM** [comment]
No we currently don't have the 20m bands in asset or export

**Comment by gilliM** [comment]
https://github.com/swisstopo/topo-satromo/pull/32

**Comment by davidoesch** [comment]
fixed with https://github.com/swisstopo/topo-satromo/pull/32
