### ISSUE TITLE
options for database out of repository

### ISSUE THREAD

**Issue by gilliM** [swisstopo/topo-satromo#3]
I find quite disturbing the use of a database as file included within the code repository. 
At least, a commit after each run should not be necessary. This pollutes the git history, making it barely usable for versioning.

Would it be possible to replace the 2 CSVs (and certainly more tables later) with an AWS RDS instance for example ? or do you have any other proposition ? a db.t4g.micro costs 15CHF per month, and would be enough for what we need.

another option would be to have those files (or more preferably a sqlite) on a s3 bucket, in the worst case.

**Comment by davidoesch** [comment]
CSV do have some advantage.. for non coders  as joan and me are

yes we shoudl store as much as possible on S3
    

-  Simplicity: Using CSV is straightforward and doesn't require specialized database knowledge. Anyone familiar with spreadsheet software can easily open and read CSV files.

-  Platform Independence: CSV is a widely supported format that can be opened on various platforms and operating systems. It's not tied to a specific database engine or technology.

-  Version Control: In GitHub, we can track and review changes to CSV files using the version control system. This facilitates collaboration and tracking of changes over time.

-  Transparency: CSV files are human-readable in plain text, increasing transparency. Anyone can inspect the content without relying on special query languages or tools.

-   Speed: Writing and reading CSV files is generally faster than working with a database, especially for small to medium-sized datasets as wer are dealing with

 -   Lower Learning Curve: People new to programming or without database experience can quickly  work with CSV files, potentially boosting productivity.

 -  Portability: CSV files can be easily moved between different systems and applications. This is useful since we need to exchange data between different tools / platforms at the early stage.

-    No Need for Server Infrastructure: Unlike databases, you don't need dedicated server infrastructure to work with CSV files in GitHub. This saves resources and effort.

-   Cost Savings: Using CSV files in GitHub is typically more cost-effective as there are no licensing fees for database software.

-   Lower Complexity: Databases can be complex and require careful data modeling. CSV files are less complex and require less planning and maintenance.

Overall, using CSV files in GitHub offers *some* advantages in *the current stage* of the project, especially for those who aren't database experts which joan and I are. However, it's important to note that the choice between CSV and databases depends on the specific requirements of our project. In the future, a database may be the better choice, particularly if we need complex queries, data integrity, or scalability.

**Comment by Rdataflow** [comment]
A very first step might be to move the logs to its own repo...

**Comment by davidoesch** [comment]
I see two options : 
A) part of the data: for every product add the corresponding log as asset (stored in S3). 


B) only for debug/operation: one log for the total run. At the end we move it to S3 .
