### ISSUE TITLE
use click for command line interface

### ISSUE THREAD

**Issue by gilliM** [swisstopo/topo-satromo#6]
I propose to build a proper command line interface, with the help of the click library. 
This way, we would have a single main file that accept arguments. 
We can add help indication to all commands and arguments for documentation, for example as benefits.
With the vision to have many different product generate, being able to launch the product generation independently is certainly a good idea.

**Comment by davidoesch** [comment]
at the moment with a simple configuration.py file  we can quickly make progress/ iterate. 
in the end we want to run the code mainly in batch mode... a pure cli could make sense in a second step

**Comment by gilliM** [comment]
@davidoesch I've got many issues trying to rebase some of my work some of changes I proposed. To continue, i would like to propose some small PR that includes each time the smallest set of feature possible, to avoid code conflicts.
The most important feature for easing my work is to be able to use a difference configuration file.
For this, i see two ways to select a configuration file: either with a environment variable, or an argument in the command line interface (like i showed in the morning).
If the command line interface is better option in your opinion, i will propose a first PR to use a command line interface instead of running the scripts directly. Then going on the configuration problem.
A third option would be that I just change the configuration file and we go on with a single configuration. That's always feasible.

What is best in your view, to use an command line argument or a environment variable ?

**Comment by davidoesch** [comment]
For us as operator of the python chain , it's important to choose a method for configuring global variables that is clear and easy to understand. In this case, I would recommend managing configuration through a configuration file rather than setting them as environment variables. Here are some reasons for this choice:

- Readability: A configuration file is generally easier to read and comprehend compared to environment variables because the values can be presented in a structured format.

 - Flexibility: With a configuration file, you can manage different settings for different environments (e.g., development, testing, production) by using different configuration files.

 - Versioning: Configuration files can be easily managed in  GitHub, enhancing traceability and collaboration.

  - Documentation: You can add comments within the configuration file to document the meaning of each setting, which improves maintainability.

Have you thought about configparser module?
``
import configparser

config = configparser.ConfigParser()
config.read('config.ini')

Accessing configuration values
S3_URL = config['S3']['url']
rclone_conf = config['RCLONE']['key']
``

**Comment by gilliM** [comment]
I'm fine with keeping python file for configuration, but i was asking how I can instruct the script about which configuration file to use, in case we want to be able to have multiple configuration file available.

**Comment by davidoesch** [comment]
define in main which file to use, maybe via Env variable?
